# -*- coding: utf-8 -*-
"""Welcome To Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

pip install pandas matplotlib seaborn

"""Python Code to Visualize Gender and Age Distribution
✅ Bar Chart for Sex (Gender)
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Load Titanic training data
df = pd.read_csv("train.csv")

# Gender count
gender_counts = df['Sex'].value_counts()

# Bar chart
plt.figure(figsize=(6,4))
sns.barplot(x=gender_counts.index, y=gender_counts.values, palette='pastel')
plt.title('Gender Distribution in Titanic Dataset')
plt.xlabel('Gender')
plt.ylabel('Count')
plt.tight_layout()
plt.savefig("gender_distribution.png")
plt.show()

"""Histogram for **Age**"""

# Drop NaN values in Age column
df = df.dropna(subset=['Age'])

# Histogram for Age
plt.figure(figsize=(6,4))
sns.histplot(df['Age'], bins=10, kde=True, color='skyblue')
plt.title('Age Distribution in Titanic Dataset')
plt.xlabel('Age')
plt.ylabel('Frequency')
plt.tight_layout()
plt.savefig("age_distribution.png")
plt.show()